askmate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('qna/',include('qna_app.urls')),
    path('user/', include('user_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from qna_app import views
from .views import QuestionListView
app_name = 'qna'


urlpatterns = [
    # path('add',views.question, name='add'),
    path('read/', views.question,name='read'),
    path('create/', views.add_question, name='create'),
    path('list/', views.list_question, name= 'list'),
    path('update/<int:id>/', views.update_question, name='update'),
    path('delete/<int:id>/', views.delete_question, name='delete'),
    path('vote_qn/<int:id>/', views.vote_question,name='vote'),
    path('listview/', QuestionListView.as_view(), name='list')
]

user_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url


urlpatterns = [

]

qna_app/models.py
from django.db import models


class CategoryModel(models.Model):
    title= models.CharField(max_length=225)
    category_desc = models.TextField()
    def __str__(self):
        return(self.title)


class QuestionModel(models.Model):
    title= models.CharField(max_length=225)
    posted_by = models.CharField( max_length= 120)
    timestamp= models.DateTimeField(auto_now_add=True)
    question_desc = models.TextField()
    question_votes = models.IntegerField(default=0)
    question_img =models.ImageField( upload_to='QuestionImg',blank=True, null=True)
    category= models.ForeignKey(CategoryModel,on_delete=models.CASCADE)

    objects = models.Manager() #solves issues in objects

    def __str__(self):
        return(self.title)
    
class AnswerModel(models.Model):
    posted_by = models.CharField(max_length=120)
    timestamp= models.DateTimeField(auto_now_add=True)
    answer_desc = models.TextField()
    answer_votes=models.IntegerField(default=0)
    answer_img =models.ImageField(upload_to='AnswerImg',blank=True, null=True)
    is_accept= models.BooleanField(default=0)
    question= models.ForeignKey(QuestionModel,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.answer_desc[:50] + '......'

user_app/models.py
from django.db import models

# Create your models here.

qna_app/forms.py
from django import forms
from .models import QuestionModel, AnswerModel , CategoryModel


class QuestionForm(forms.ModelForm):
    class Meta:
        model=QuestionModel
        fields='__all__'



class AnswerForm(forms.ModelForm):
    class Meta:
        model=AnswerModel
        fields='__all__'

qna_app/views.py
from django.shortcuts import render, redirect
from .models import QuestionModel, AnswerModel, CategoryModel
from .forms import QuestionForm, AnswerForm # importing form to display
from django.http import HttpResponse
from django.views.generic import CreateView, ListView


def question(request):
    Question = QuestionModel.objects.all()
    return render(request,'question.html',{'question':Question})

def list_question(request):
    Question = QuestionModel.objects.all()
    return render(request, 'qna_app/list.html', {'question': Question})


def add_question(request):

    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('qna:read')

        else:
            print(form.errors)
            return HttpResponse('Invalid Form')


    else:

        #form = QuestionForm
        category= CategoryModel.objects.all()
        return render(request, 'qna_app/create.html', {'category': category})


def update_question(request, id):
    ques = QuestionModel.objects.get(id=id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES, instance=ques)

        if form.is_valid():
            form.save()
            return redirect('qna:list')

        else:
            return HttpResponse('Invalid Form')

    else:
        form = QuestionForm(instance=ques)
        return render(request, 'qna_app/update.html/', {'form': form})


def delete_question(request, id):
    ques = QuestionModel.objects.get(id=id)
    ques.delete()
    return redirect('qna:list')


def vote_question(request, id):
    instance = QuestionModel.objects.get(id=id)
    vote = instance.question_votes +1
    instance.question_votes = vote
    instance.save()
    return redirect('qna:read')

def answer(request,id):
    if request.method == "POST":
        by= request.POST.get('answered_by')
        desc = request.POST.get('answer_desc')
        answer_img = request.POST.get('answer_img')
        question = QuestionModel.objects.get(id=id)
        Comment = AnswerModel(answered_by=by, answer_desc=desc, answer_img=answer_img,
        question=question)
        Comment.save()
        return HttpResponse('SUCCESS')
    else:
        form= AnswerForm
        a={'form':form}
        b={'id':id}
        c={**a,**b}
        return render(request,'ans_create.html')


class QuestionListView(ListView):
    queryset = QuestionModel.objects.all()

user_app/views.py
from django.shortcuts import render

# Create your views here.

qna_app/templates/ans/create.html
<form method="post" enctype="multimedia/form-data">
    {% csrf_token %}
    Name*: <input type="text" name="answered_by">
    Comment*= <input type="text" name="answer_desc">
    Image: <input type="file" name="answer_img">
    <input type="submit" value="Submit" />
</form>

qna_app/templates/qna_app/create.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
Title: <input type="text" name="title"> <br> <br>
Posted By:  <input type="text" name="posted_by"> <br> <br>
<!--    Describtion: <input type="text" name="question_desc"><br><br>-->
Describtion: <br>
    <textarea name="question_desc" cols="40" rows="10" class="vLargeTextField" required="" id="id_question_desc">   </textarea>
<br> <br>
    Image: <input type="file" name ="question_img"> <br><br>
<select name="category">
    {% for cat in category %}

    <option value="{{cat.id}}">
    {{cat.title}}
    </option>

    {% endfor %}



</select>
<input type="hidden" name="question_votes" value='0'>
    <input type="submit" value="Submit">
</form>

qna_app/templates/qna_app/list.html
<html>
<body>


 <h1> QUESTIONS: </h1>
    {% for q in question %}
    <h1>{{q.category}}</h1>
    <h2>{{q.question_desc}}</h2>

    <img src="../../media/{{q.question_img}}" style="width:100px;height: 100px;"/>
   <br>

 <a href="{% url 'qna:update' q.id %}"><button>Update</button></a>
 <a href="{% url 'qna:delete' q.id %}"><button>Delete</button></a>
<a href="{% url 'qna:vote' q.id %}"><button>Vote</button></a>



    {% endfor %}

</body>


</html>

qna_app/templates/qna_app/questionmodel_list.html
 {% for q in object_list %}
    <h1>{{q.category}}</h1>
    <h2>{{q.question_desc}}</h2>

    <img src="../../media/{{q.question_img}}" style="width:100px;height: 100px;"/>
   <br>

 <a href="{% url 'qna:update' q.id %}"><button>Update</button></a>
 <a href="{% url 'qna:delete' q.id %}"><button>Delete</button></a>
<a href="{% url 'qna:vote' q.id %}"><button>Vote</button></a>



    {% endfor %}

qna_app/templates/qna_app/update.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

qna_app/templates/question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body style='background-color: #3b19d1;'>
   <h1> QUESTIONS: </h1> 
    {% for q in question %}
    <h1>{{q.category}}</h1>
    <h2>{{q.question_desc}}</h2>


    <img src="../../media/{{q.question_img}}" style="width:100px;height: 100px;"/>
   <h2> vote: {{q.question_votes}} </h2>

   <br>
    {% endfor %}


</body>
</html>